### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by IRONB0SS** [daidr/dualsense-tester#6]
Hey Sir and all dear contributors, How are you
first of all thanks a lot for the tool, it's amazing and best tester by miles, You sir are genius.

I want to host this tool on my website so I've downloaded [source files](https://github.com/daidr/dualsense-tester/archive/refs/heads/main.zip) but couldn't find index.html, what shall I do?

**Feedback:**
is it possible to implement these somehow? [Website](https://hardwaretester.com/gamepad)
![image](https://github.com/user-attachments/assets/c8803c05-0238-4fe5-9152-89b200472007)

also it would be awesome to support PS4, PS3 and Xbox controllers too, thanks in advance

is there any possibility to connect the controller with hitting any button of the controller and not with connect button?

**Comment by IRONB0SS** [comment]
@daidr Hey

**Comment by daidr** [comment]
Sorry, I just saw your issue.

If you want to deploy it on your server, you need to build it yourself.

```
pnpm install
pnpm build
```

The numerical display of pressure will be added in the next version.

At present, only dualsense is supported. Because I don't have a ps4 controller, I don't consider supporting it for the time being.

**Comment by IRONB0SS** [comment]
thanks a lot

**Comment by IRONB0SS** [comment]
Hey, thanks for the update

please add this too

<img width="331" alt="Screenshot 2024-10-21 033743" src="https://github.com/user-attachments/assets/dbb524c2-33f5-43e0-8de1-17cd1e8cfc8c">

**Comment by daidr** [comment]
> Hey, thanks for the update
> 
> 
> 
> please add this too
> 
> 
> 
> <img width="331" alt="Screenshot 2024-10-21 033743" src="https://github.com/user-attachments/assets/dbb524c2-33f5-43e0-8de1-17cd1e8cfc8c">

Thank you for your suggestion. This feature will be added in the next release. 😀

**Comment by IRONB0SS** [comment]
And last thing
My Android chrome is updated so what is the problem?

![Screenshot_20241021_140452_Chrome.jpg](https://github.com/user-attachments/assets/1fc096d4-9999-4423-87dc-6d8349f82c86)

**Comment by daidr** [comment]
> And last thing
> My Android chrome is updated so what is the problem?
> 
> ![Screenshot_20241021_140452_Chrome.jpg](https://github.com/user-attachments/assets/1fc096d4-9999-4423-87dc-6d8349f82c86)
> 
> 

https://caniuse.com/?search=webhid

Only desktop browsers have webHID support currently.

**Comment by IRONB0SS** [comment]
Another one last thing 

Do you accept freelancer job? I want this for dualsense and dualshock, If you accept please tell me how much is the cost, thanks in advance 

![Screenshot_20241021_154159_Samsung Internet.jpg](https://github.com/user-attachments/assets/e951b675-5eb9-449a-b51f-4dedc33a2f18)


https://xboxdesignlab.xbox.com/en-us/configure/xbox-wireless-controller?recipeId=T27NJ228

**Comment by IRONB0SS** [comment]
?

**Comment by daidr** [comment]
> Another one last thing 
> 
> Do you accept freelancer job? I want this for dualsense and dualshock, If you accept please tell me how much is the cost, thanks in advance
> 
> ![Screenshot_20241021_154159_Samsung Internet.jpg](https://github.com/user-attachments/assets/e951b675-5eb9-449a-b51f-4dedc33a2f18)
> 
> 
> https://xboxdesignlab.xbox.com/en-us/configure/xbox-wireless-controller?recipeId=T27NJ228

I'm not sure what you're referring to. Are you talking about adding DualShock support, or are you looking to achieve the styling effect shown in the image?

**Comment by IRONB0SS** [comment]
Hey again, please open the link
Xbox offers fully customize controller by your own in 360 view so I want to have design lab for dualsense too but with limited options

![IMG_20241027_122707_997.jpg](https://github.com/user-attachments/assets/600c8a1e-811b-41da-90be-c6f8ebc4e19c)

**Comment by IRONB0SS** [comment]
Hey Buddy, what's up?
here the leaked dualsense tester app via sony
we can inspire a lot of things from this app for example beep sound from speaker was good idea also better analog tester
<img width="129" alt="image" src="https://github.com/user-attachments/assets/22ee6944-159d-4f34-a5e1-22db85bc3498">
![image](https://github.com/user-attachments/assets/d143e096-2519-4332-a580-a259f8ebf35c)

please add this features, thanks a lot

[DuelSense official test app + Guide .zip](https://github.com/user-attachments/files/18087446/DuelSense.official.test.app.%2B.Guide.zip)

**Comment by daidr** [comment]
> Hey Buddy, what's up? here the leaked dualsense tester app via sony we can inspire a lot of things from this app for example beep sound from speaker and testing mic was good idea also better analog tester <img alt="image" width="129" src="https://private-user-images.githubusercontent.com/97769328/394501793-22ee6944-159d-4f34-a5e1-22db85bc3498.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4OTU2MTAsIm5iZiI6MTczMzg5NTMxMCwicGF0aCI6Ii85Nzc2OTMyOC8zOTQ1MDE3OTMtMjJlZTY5NDQtMTU5ZC00ZjM0LWE1ZTEtMjJkYjg1YmMzNDk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjExVDA1MzUxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhYzdlNWJhYjNmZjIyOGNhNGI3NmZhNzYwZTcxYjg2NTg2NzA1OGFhM2EzZjhhM2I4N2ZjNDg3MzYwYTFlZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qSMczjysChYmO_1jO1LmqQyx2QdnYblFwNbJh70JWn4"> ![image](https://private-user-images.githubusercontent.com/97769328/394501835-d143e096-2519-4332-a580-a259f8ebf35c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4OTU2MTAsIm5iZiI6MTczMzg5NTMxMCwicGF0aCI6Ii85Nzc2OTMyOC8zOTQ1MDE4MzUtZDE0M2UwOTYtMjUxOS00MzMyLWE1ODAtYTI1OWY4ZWJmMzVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjExVDA1MzUxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmY2Y0OTFiODQ3MGNlYjEyMTE3MGMwZDA5MzMzNjU5ZDJiNGFlYmI3OTdlNjVlNjk5NGYzYTQ0YzY0ZjhiZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MZEzX0vxhTM5vy628ZOJKU-Y3YTz96YiS50y6Ziw3fs)
> 
> please add this features, thanks a lot
> 
> [DuelSense official test app + Guide .zip](https://github.com/user-attachments/files/18087446/DuelSense.official.test.app.%2B.Guide.zip)

I am currently refactoring to add multi-controller support, and the joystick indicator mentioned above will be updated by the end of this weekend.

**Comment by IRONB0SS** [comment]
> I am currently refactoring to add multi-controller support, and the joystick indicator mentioned above will be updated by the end of this weekend.

Awesome, thanks a lot ❤️

**Comment by IRONB0SS** [comment]
> I am currently refactoring to add multi-controller support

this is "PS3 Gamepad tester.pkg" source code, Is it useful?

[PS3_GamePadTest_src.zip](https://github.com/user-attachments/files/18178272/PS3_GamePadTest_src.zip)

**Comment by IRONB0SS** [comment]
Hello again, I've investigate about Xbox 360 controllers and seems like there is no way to test them without this adapter
![61Ay5cqVBaL._AC_SL1500_.jpg](https://github.com/user-attachments/assets/d7ba593b-105f-41a6-bf57-3d19219128c8)

**Comment by daidr** [comment]
I'm attempting to provide DualSense Edge testing currently. 

If you have any new ideas, you can open a new issue for discussion. It's difficult to notice comments within the same closed issue.

**Comment by IRONB0SS** [comment]
> I'm attempting to provide DualSense Edge testing currently. 
> 
> If you have any new ideas, you can open a new issue for discussion. It's difficult to notice comments within the same closed issue.
> 

Sure buddy, good luck and thanks a lot
Did you update your website too? Cause I didn't see "stick cross line update"

**Comment by daidr** [comment]
> > If you have any new ideas, you can open a new issue for discussion.
> 
> Sure buddy, good luck and thanks a lot
> Did you update your website too? Cause I didn't see "stick cross line update"
> 
> Edit: new update is very cool, thanks a lot genius, very clever implementation 🙌❤️

Try switching to "Value display on" and you should see the joystick indicator
